"""Mock LLM adapter for testing without a real API key.

Returns deterministic, predictable responses. Used as default
adapter when no API key is configured.
"""

from __future__ import annotations

import json
from typing import Any


class MockLLMAdapter:
    """A deterministic mock LLM for testing.

    Returns pre-configured responses or generates simple patterns
    based on the input. Supports JSON mode.
    """

    def __init__(self, responses: dict[str, str] | None = None) -> None:
        self.responses = responses or {}

    def generate(
        self,
        system_prompt: str,
        user_message: str,
        temperature: float = 0.7,
        max_tokens: int = 2048,
    ) -> str:
        """Return a mock response. Checks registered responses first,
        then falls back to a simple echo-based reply."""
        key = self._make_key(system_prompt, user_message)
        if key in self.responses:
            return self.responses[key]

        return self._default_response(system_prompt, user_message)

    def generate_json(
        self,
        system_prompt: str,
        user_message: str,
        temperature: float = 0.3,
        max_tokens: int = 4096,
    ) -> dict[str, Any]:
        """Return a mock JSON response."""
        text = self.generate(system_prompt, user_message, temperature, max_tokens)
        try:
            return json.loads(text)
        except json.JSONDecodeError:
            return {"raw_text": text}

    def _make_key(self, system_prompt: str, user_message: str) -> str:
        return f"{system_prompt[:100]}|{user_message[:100]}"

    def _default_response(self, system_prompt: str, user_message: str) -> str:
        """Generate a simple deterministic response.

        Uses the system prompt to identify the task and returns
        appropriate mock data. Conditions are ordered by specificity.
        """
        sp_lower = system_prompt.lower()

        # Contradiction detection
        if "contradiction detection" in sp_lower:
            return json.dumps(
                {
                    "contradictions": [
                        {
                            "memory_a": "mock_mem_1",
                            "memory_b": "mock_mem_2",
                            "description": "Mock contradiction between two memories",
                            "severity": "medium",
                        }
                    ]
                }
            )

        # Literature recommendation
        if "recommendation" in sp_lower or "literature" in sp_lower:
            return json.dumps(
                {
                    "queries": [
                        "mock query: recent advances in relevant field",
                        "mock query: related methodology improvements",
                    ],
                    "user_actions": [
                        "Search for recent clinical trials on the topic",
                        "Review related methodology papers for experimental design",
                    ],
                    "reasoning": "Mock reasoning for literature recommendations",
                }
            )

        # Project summary consolidation
        if "summary consolidation" in sp_lower:
            return (
                "Mock project summary generated by MockLLMAdapter. "
                "The project investigates key research questions "
                "using established methodologies."
            )

        # --- Paper Learning Library extractors ---

        # Experiment design extraction
        if "experiment design" in sp_lower:
            return json.dumps(
                {
                    "research_question": "How does the experimental treatment modulate the biological response?",
                    "hypothesis": "The treatment activates the relevant signaling pathway to modulate cellular function",
                    "experimental_models": ["Model cell line A", "Animal model B"],
                    "groups": ["Control (untreated)", "Treatment low dose", "Treatment medium dose", "Treatment high dose"],
                    "interventions": ["Experimental treatment", "Positive control stimulation"],
                    "doses_or_concentrations": ["low dose", "medium dose", "high dose"],
                    "timepoints": ["0 h", "6 h", "12 h", "24 h", "48 h"],
                    "assays": ["Cell viability assay", "ELISA for cytokine quantification", "qPCR for gene expression", "Western blot for protein expression"],
                    "controls": ["Untreated control", "Positive control"],
                    "statistical_methods": ["One-way ANOVA", "Tukey's post-hoc test", "Student's t-test"],
                    "validation_chain": ["Cell viability confirmed before treatment → Dose-response established → Target validation via Western blot → Mechanism confirmed via inhibitor assay"],
                    "strengths": ["Multiple orthogonal assays used", "Both in vitro and in vivo models", "Dose-response and time-course data"],
                    "limitations": ["Limited cell types tested", "Mechanism not fully elucidated"],
                }
            )

        # Mechanism pathway extraction
        if "mechanism extraction" in sp_lower:
            return json.dumps(
                {
                    "pathway": "Example signaling pathway",
                    "targets": ["Target A", "Target B", "Target C"],
                    "upstream_factors": ["Factor X", "Factor Y", "Factor Z"],
                    "downstream_readouts": ["Readout 1", "Readout 2", "Readout 3"],
                    "evidence_types": ["Western blot", "qPCR", "ELISA", "Immunofluorescence"],
                    "claim_strength": "strong",
                    "limitations": ["Knockout experiment not performed", "Upstream receptor not definitively identified", "Only canonical pathway examined"],
                }
            )

        # Figure logic extraction
        if "figure logic" in sp_lower:
            return json.dumps(
                {
                    "figure_logics": [
                        {
                            "figure_id": "Figure 1",
                            "figure_role": "phenotypic_characterization",
                            "data_type": "bar_chart",
                            "key_message": "Treatment significantly increased key effectors in a dose-dependent manner without cytotoxicity",
                            "supports_which_claim": "Treatment activates the biological response",
                            "reusable_figure_idea": "Dose-response bar chart with multiple readouts normalized to control",
                        },
                        {
                            "figure_id": "Figure 2",
                            "figure_role": "mechanism_probing",
                            "data_type": "western_blot",
                            "key_message": "Treatment upregulated phosphorylated signaling proteins, indicating pathway activation",
                            "supports_which_claim": "Treatment activates response through specific signaling",
                            "reusable_figure_idea": "Time-course Western blot of signaling proteins with densitometry quantification",
                        },
                        {
                            "figure_id": "Figure 3",
                            "figure_role": "mechanism_confirmation",
                            "data_type": "microscopy",
                            "key_message": "Key transcription factor translocates from cytoplasm to nucleus upon treatment, confirming pathway activation",
                            "supports_which_claim": "Treatment induces nuclear translocation",
                            "reusable_figure_idea": "Immunofluorescence co-staining showing nuclear translocation with quantification",
                        },
                    ]
                }
            )

        # Writing pattern extraction
        if "writing pattern" in sp_lower:
            return json.dumps(
                {
                    "writing_patterns": [
                        {
                            "introduction_logic": "Funnel structure: broad context → specific research gap → explicit hypothesis",
                            "result_narrative": "Figure-guided narrative: each figure presented sequentially with descriptive heading, followed by key statistical comparisons and biological interpretation",
                            "discussion_logic": "Reverse funnel: restate key findings → compare with literature → mechanistic synthesis → acknowledge limitations → propose applications",
                            "novelty_framing": "Emphasises first demonstration of the mechanism, highlighting the novelty of the approach",
                            "limitation_framing": "Limitations are grouped in a dedicated paragraph near the end of discussion, presented as 'future directions' rather than weaknesses",
                            "application_framing": "Final paragraph positions the finding as a potential basis for further research or application development",
                            "reusable_sentences_or_templates": [
                                "'These findings suggest that [intervention] modulates [pathway] through [mechanism], providing a rationale for [application].'",
                                "'To further elucidate the molecular mechanism, we examined [target] using [method].'",
                                "'Taken together, our results demonstrate that [finding], highlighting the potential of [intervention] for [application].'",
                            ],
                        },
                    ]
                }
            )

        # Paper/pattern extraction (default for research-related prompts)
        return json.dumps(
            {
                "research_question": "Mock research question from input",
                "core_logic": "Mock experimental logic flow",
                "experimental_models": ["Cell line A", "Model organism B"],
                "assays": ["Western blot", "qPCR", "Immunofluorescence"],
                "mechanisms": ["Example pathway activation"],
                "omics_methods": ["RNA-seq"],
                "statistical_methods": ["t-test", "ANOVA"],
                "innovations": ["Novel finding from mock LLM"],
                "limitations": ["Limited sample size"],
                "reusable_insights": ["Consider using similar model system"],
            }
        )
